### ISSUE TITLE
Template generator appending [] to import statments of lists

### ISSUE THREAD

**Issue by William-Sudletsky** [bergerhealer/Mountiplex#2]
Ex:
```Java
class Chunk {
    public final (Set[]) EntitySlice<Entity>[] entitySlices;

    public (BlockData) IBlockData getBlockData((IntVector3) BlockPosition blockposition);
}
```

In this case, Mountiplex will place `import java.util.Set[];` within ChunkHandler.

**Comment by bergerkiller** [comment]
Oh I ran into this myself too, but it has been fixed now.
https://github.com/bergerhealer/Mountiplex/commit/7d705a53b53d862e743468e05126d7f0b046f06b
